# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.27.044601'

RELEASE_GIT_HEAD = 'e6a100646ed320975077132b3a8532f195d17a5d'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'ddx-ai/yt-dlp'

ORIGIN = 'ddx-ai/yt-dlp'

_pkg_version = '2024.12.27.044601'
