# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.01.151736'

RELEASE_GIT_HEAD = '510c51c48deaf1b44e2635a50d7977550d416a6a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'ddx-ai/yt-dlp'

ORIGIN = 'ddx-ai/yt-dlp'

_pkg_version = '2024.12.01.151736'
