# Autogenerated by devscripts/update-version.py

__version__ = '2024.12.24.141934'

RELEASE_GIT_HEAD = 'ca07e4841ecd93e0e6ec930b5bd49a3542931d5b'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'ddx-ai/yt-dlp'

ORIGIN = 'ddx-ai/yt-dlp'

_pkg_version = '2024.12.24.141934'
